const steps = ['Introduced', 'Passed One House', 'Passed Both', 'To President', 'Signed into Law'];
let bills = [
  { bill_id:"H.R. 28", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/28", title:"Protection of Women and Girls in Sports Act of 2025", partySupport:"Republican", summary:"<p><strong>Protection of Women and Girls in Sports Act of 2025</strong></p><p>This bill generally prohibits school athletic programs from allowing individuals whose biological sex at birth was male to participate in programs that are for women or girls.</p><p>Specifically,the bill provides that it is a violation of Title IX of the Education Amendments of 1972 for federally funded education programs or activities to operate,sponsor,or facilitate athletic programs or activities that allow individuals of the male sex to participate in programs or activities that are designated for women or girls. (Title IX prohibits discrimination on the basis of sex in federally funded education programs or activities,including in public elementary and secondary schools and in colleges and universities.) Under the bill,<em> sex</em> is based on an individual's reproductive biology and genetics at birth.</p><p>The bill does not prohibit male individuals from training or practicing with programs or activities for women or girls as long as such training or practice does not deprive any female of corresponding opportunities or benefits.</p><p>The Government Accountability Office must report on the benefits for women or girls in single-sex sports that would be lost as a result of male participation. In particular,the report must document the negative psychological,developmental,participatory,and sociological effects of male participation on girls.</p>", currentStep:"Passed One House", tags: ['Passed One House','LGBTQ','Transgender','Pinned'] },
  { bill_id:"H.R. 1282", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1282", title:"To prohibit Federal funding for institutions of higher education that carry out diversity,equity,and inclusion initiatives,and for other purposes.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced','LGBTQ','DEI'] },
    { bill_id:"H.R. 1139", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1139", title:"To prohibit the Secretary of State from issuing a passport,passport card,or Consular Report of Birth Abroad that includes the unspecified (X) gender designation,and for other purposes.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced','LGBTQ','Transgender','Pinned'] },
    { bill_id:"H.R. 1028", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1028", title:"To modify eligibility requirements for amateur sports governing organizations.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
    { bill_id:"H.R. 1017", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1017", title:"To prohibit an entity from receiving Federal funds if such entity permits an individual to access or use a single-sex facility on the property of such entity that does not correspond to the biological sex of such person,and for other purposes.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced','LGBTQ','Transgender','Pinned'] },
    { bill_id:"H.R. 1016", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1016", title:"To prohibit individuals from accessing or using single-sex facilities on Federal property other than those corresponding to their biological sex,and for other purposes.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
    { bill_id:"H.R. 1015", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/1015", title:"To amend title 18,United States Code,to provide for certain rules for housing or transportation based on gender and to provide for a limitation on gender-related medical treatment.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
   { bill_id:"H.R. 742", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/742", title:"To prohibit Federal funds from being used to provide certain gender transition procedures to minors.", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
   { bill_id:"H.R. 653", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/653", title:"Protect Minors from Medical Malpractice Act of 2025", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
   { bill_id:"H.R. 498", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/498", title:"Do No Harm in Medicaid Act", partySupport:"Republican", summary:"<p><strong>Do No Harm in Medicaid Act</strong></p><p>This bill prohibits federal Medicaid payment for specified gender transition procedures for individuals under the age of 18. The bill defines these procedures to mean those that are intended to change the body of an individual to no longer correspond to the individual's biological sex (male or female),including specified surgeries,implants,and medications (e.g.,hormones).</p><p>The bill excludes procedures that are provided to an individual under the age of 18 with the consent of a parent or legal guardian and that are intended to (1) rectify early puberty,genetic disorders,or chromosomal abnormalities; (2) reverse prior gender transition procedures; or (3) prevent imminent death or impairment of a major bodily function.</p>", currentStep:"Introduced", tags: ['Introduced'] },
    { bill_id:"H.R. 461", govtrack_url:"https://www.congress.gov/bill/119th-congress/house-bill/461", title:"Eliminate DEI in the Military Act", partySupport:"Republican", summary:"", currentStep:"Introduced", tags: ['Introduced'] },
    ]
    
 ;

export const getBills = () => {
  return bills;
};

export const setBills = (newBills) => {
  bills = newBills;
};

export const getSteps = () => {
  return steps;
};
